name: Deploy Docs

on:
  push:
    branches: main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:

  deploy-docs:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Mkdocs
        run: |
          python -m pip install mkdocs-material
      - name: Deploy Docs
        run: |
          mkdocs build
      - uses: actions/configure-pages@v3
      - uses: actions/upload-pages-artifact@v1
        with:
          path: site
      - name: Deploy to GitHub Pages
        id: deploy-pages
        uses: actions/deploy-pages@v3
